### ISSUE TITLE
It returns gibberish

### ISSUE THREAD

**Issue by kokinarido** [partim/domain#17]
I want to retrieve **only MX**

  ```
      let mut core = Core::new().unwrap();
      let resolv = Resolver::new(&core.handle());
      let name = DNameBuf::from_str("www.rust-lang.org.").unwrap();

      let mx_req = resolv.query((name, Rtype::Mx, Class::In));
      let mx = core.run(mx_req).unwrap();

      for record in mx.answer().unwrap() {
          println!("{}", record.unwrap());
      }

```
But the answer contains only CNAME. 
Also, why does it require the dot in the end of a URL? Otherwise it panics at runtime.

**Comment by partim** [comment]
The `CNAME` indicates that `www.rust-lang.org.` is in an alias to the name stated in the record. It is present in the answer so that you can follow the chain as any records actually answering your query would have that name as their domain name. That there is no `MX` records under that name in the answer indicates that there is no `MX` records there, which is indeed the case. In other words, there is no `MX` records for your query; the response is actually correct. 

The missing final dot indicates a relative domain name (one that does not end with the root label). Queries only work with absolute domain names. Please have a look at [`lookup_records()`](https://docs.rs/domain/0.2.1/domain/resolv/lookup/records/fn.lookup_records.html) for a way to use these relative names.

That it panics in the query is a bit unfortunate. I am considering distinguishing between absolute and relative names on the type level. I haven't done that yet, though, since that would mean two more domain name types and there's too many already.

**Comment by kokinarido** [comment]
there're no mx for www.rust-lang.org, but for example for     

```
    let name1 = DNameBuf::from_str("www.jelastic.com.").unwrap();
    let name2 = DNameBuf::from_str("jelastic.com.").unwrap();
```
yes, the 1st one has CNAME. nonetheless, shouldn't they both return MX records? only the 2nd one returns 
 them.

**Comment by kokinarido** [comment]
when I'm doing this:

```
    for record in mx.answer().unwrap() {
        println!("{}", record.unwrap());
    }

```

it prints a whole line of an answer. how can I get only the part containing the "value" part

```
my_domain.com.       1234    IN      MX      50 mx3.some_email_hosting.com.
my_domain.com.       1234    IN      MX      20 mx2.some_email_hosting.com.
my_domain.com.       1234    IN      MX      10 mx.some_email_hosting.com.

```
In this case it's  "mx.some_email_hosting.com." and  "mx2.some_email_hosting.com."  
 and "mx3.some_email_hosting.com."

**Comment by partim** [comment]
You can iterate over specific types by using `limit_to()` on the answer section:

```
use domain::bits::{Message, ParseResult};
use domain::rdata::parsed::Mx;

fn process_mx(msg: &Message) -> ParseResult<Vec<(u16,DNameBuf)>> {
    let mut res = Vec::new();
    for record in msg.answer()?.limit_to::<Mx>() {
        let record = try!(record);
        res.push((record.preference(), record.exchange().to_cow().into_owned()));
    }
    Ok(res)
}
```

**Comment by kokinarido** [comment]
thanks.

**Comment by kokinarido** [comment]
I have the code similar to yours:

```
    let mx_req = resolv.query((name, Rtype::Mx, Class::In));
    let mx = core.run(mx_req).unwrap();
    for r in mx.answer()?.limit_to::<Mx>() { # doesn't compile
            println!("{:?}", r.unwrap());
    }
```

The 3rd line doesn't compile:

```
 error[E0277]: the trait bound `(): std::ops::Carrier` is not satisfied
     for r in mx.answer()?.limit_to::<Mx>() {

```

**Comment by partim** [comment]
I guess you have to replace the question mark with an `unwrap()` if you don't do this inside a function that returns a `Result`.

**Comment by kokinarido** [comment]
then "record" will contain no functions called "preference()", "exchange()".

`RecordSection { parser: Parser { bytes: [...........], section: Answer, count: Ok(3) }`

**Comment by partim** [comment]
Sorry, yes: those are part of the data.

```
    for r in mx.answer().unwrap().limit_to::<Mx>() { 
        let r = r.unwrap();
        println!("{} {}", r.data().preference(), r.data().exchange());
    }
```

**Comment by kokinarido** [comment]
`    for r in mx.answer().unwrap().limit_to::<Mx>(){ ---> error[E0243]: wrong number of type arguments: expected 1, found 0
`

**Comment by partim** [comment]
You need to import `Mx` from `domain::rdata::parsed`. The normal `Mx` type is generic over the domain name type, so you actually need to supply `Mx<ParsedDName>` for which there is a type alias in the `domain::rdata::parsed` module.

**Comment by kokinarido** [comment]
it's already been imported:

`use domain::rdata::Mx;`

You have` .limit_to::<Mx>` without `<ParsedDName>`

Will you show me the whole code?

**Comment by kokinarido** [comment]
`for r in mx.answer().unwrap().limit_to::<domain::rdata::parsed::Mx>()` 

error:
```

        error: no method named `preference` found for type 
       `std::result::Result<domain::bits::Record<domain::bits::ParsedDName<'_>, 
         domain::rdata::Mx<domain::bits::ParsedDName<'_>>>, domain::bits::ParseError>` in the current scope
```

**Comment by partim** [comment]
Did you use both `unwrap()` and `data()` in the loop’s body as suggested a few comments back?

```
    use domain::rdata::parsed::Mx;

    for r in mx.answer().unwrap().limit_to::<Mx>() { 
        let r = r.unwrap();
        println!("{} {}", r.data().preference(), r.data().exchange());
    }
```

**Comment by kokinarido** [comment]
thanks.
