### ISSUE TITLE
Crashed in Query

### ISSUE THREAD

**Issue by zonyitoo** [partim/domain#20]
I have received some reports of crashes at https://github.com/partim/domain/blob/master/src/resolv/public.rs#L306

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.2.1/src/resolv/public.rs:306
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by zonyitoo** [comment]
@partim Please publish this patch :)

**Comment by partim** [comment]
Thanks for the report. I think the commit fixes the issue. I know I should have some test cases for it, however, I am in the middle of some changes, one goal of which is to make testing easier.

Meanwhile, I’ll try to reproduce the error and test the patch manually before releasing. Give me a minute ;)

**Comment by zonyitoo** [comment]
Sure. Thanks!

**Comment by partim** [comment]
Just release 0.2.2. Sorry about the blunder …

**Comment by zonyitoo** [comment]
Thanks!
